{% set version = '0.0-6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rpython
  version: {{ version|replace("-", "_") }}

source:
  fn: rPython_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rPython_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rPython/rPython_{{ version }}.tar.gz


  sha256: b7e1cc797bdca6b574735b4e657ad9bd94080c8d3e943c350b09f15a889589ab
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - r-rjsonio >=0.7_3
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-rjsonio >=0.7_3
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]
    - python

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rPython')"  # [not win]
    - "\"%R%\" -e \"library('rPython')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http
  license: GPL-2
  summary: Run Python code, make function calls,  assign and retrieve variables, etc. from R.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: rPython
# Version: 0.0-6
# Date: 2015-11-15
# Title: Package Allowing R to Call Python
# Author: Carlos J. Gil Bellosta
# Maintainer: Carlos J. Gil Bellosta <cgb@datanalytics.com>
# Description: Run Python code, make function calls,  assign and retrieve variables, etc. from R.
# Depends: RJSONIO (>= 0.7-3)
# License: GPL-2
# SystemRequirements: Python (>= 2.7) and Python headers and libraries (See the INSTALL file)
# OS_type: unix
# URL: http://rpython.r-forge.r-project.org/
# NeedsCompilation: yes
# Packaged: 2015-11-15 20:42:54 UTC; carlos
# Repository: CRAN
# Date/Publication: 2015-11-15 22:27:07

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
