{% set version = '0.0-6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rpython
  version: {{ version|replace("-", "_") }}

source:
  fn: rPython_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rPython_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rPython/rPython_{{ version }}.tar.gz
  sha256: b7e1cc797bdca6b574735b4e657ad9bd94080c8d3e943c350b09f15a889589ab

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-rjsonio >=0.7_3
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]
    - python

  run:
    - r-base
    - r-rjsonio >=0.7_3
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]
    - python

test:
  commands:
    - $R -e "library('rPython')"  # [not win]
    - "\"%R%\" -e \"library('rPython')\""  # [win]

about:
  home: http
  license: GPL-2
  summary: Run Python code, make function calls,  assign and retrieve variables, etc. from R.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - afust
